version: '3'
services:
  gin-dev:
    image: runqukunf/gin-dev
    container_name: gin-dev
    ports:
      - 80:8080
    volumes:
      - .:/golangGinBlog
    networks:
      - gogin-dev

networks:
  gogin-dev:

    